import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | BarberLine AI",
  description:
    "Learn how BarberLine AI collects, uses, and protects your personal information.",
};

export default function PrivacyPolicyPage() {
  return (
    <section className="relative py-28">
      <div className="container relative mx-auto px-6">
        {/* Header */}
        <div className="mx-auto max-w-3xl text-center">
          <span className="text-xs font-medium uppercase tracking-[0.1em] text-gold">
            Legal
          </span>
          <h1 className="mt-4 font-sans font-bold text-4xl tracking-tight sm:text-5xl text-cream">
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm text-warm-gray">
            Effective Date: February 26, 2026
          </p>
          <div className="gold-line mx-auto mt-8 w-24" />
        </div>

        {/* Body */}
        <div className="mx-auto mt-16 max-w-3xl">
          <p className="text-sm leading-relaxed text-warm-gray">
            BarberLine AI (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;)
            operates a software-as-a-service platform that provides AI-powered
            phone receptionist services for barbershops. This Privacy Policy
            explains how we collect, use, disclose, and safeguard your
            information when you use our website and services. Please read this
            policy carefully. By accessing or using BarberLine AI, you agree to
            the terms of this Privacy Policy.
          </p>

          {/* 1. Information We Collect */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            1. Information We Collect
          </h2>

          <h3 className="mt-6 mb-2 font-sans font-bold text-lg text-cream/80">
            Account Information
          </h3>
          <p className="text-sm leading-relaxed text-warm-gray">
            When you create an account, we collect your name and email address
            through our authentication provider, Clerk. If you register as a
            barbershop owner, we also collect your business name, business
            address, phone number, and other shop details you provide.
          </p>

          <h3 className="mt-6 mb-2 font-sans font-bold text-lg text-cream/80">
            Phone Call Data
          </h3>
          <p className="text-sm leading-relaxed text-warm-gray">
            Our AI receptionist service processes inbound phone calls on behalf
            of your barbershop. In connection with this service, we collect:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6 text-sm leading-relaxed text-warm-gray">
            <li>
              Phone numbers of callers who contact your barbershop through our
              service
            </li>
            <li>
              Call recordings and transcripts generated by our voice AI provider,
              Vapi
            </li>
            <li>Call duration, timestamps, and call outcome metadata</li>
            <li>
              Caller intent and extracted booking details (e.g., requested
              service, preferred barber, date and time)
            </li>
          </ul>

          <h3 className="mt-6 mb-2 font-sans font-bold text-lg text-cream/80">
            Booking Data
          </h3>
          <p className="text-sm leading-relaxed text-warm-gray">
            When our AI assistant books appointments on behalf of callers, we
            collect and store booking details including appointment date and
            time, selected service, barber assignment, and customer contact
            information. This data is also transmitted to your connected Square
            account.
          </p>

          <h3 className="mt-6 mb-2 font-sans font-bold text-lg text-cream/80">
            Usage and Analytics Data
          </h3>
          <p className="text-sm leading-relaxed text-warm-gray">
            We automatically collect certain information when you access our
            platform, including IP address, browser type, device information,
            pages visited, and interaction patterns. We also generate aggregated
            analytics about call volumes, booking rates, and service performance.
          </p>

          {/* 2. How We Use Your Information */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            2. How We Use Your Information
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            We use the information we collect for the following purposes:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6 text-sm leading-relaxed text-warm-gray">
            <li>
              To provide, operate, and maintain our AI receptionist service,
              including answering calls, booking appointments, and sending
              confirmations
            </li>
            <li>
              To create and manage your account and authenticate your identity
            </li>
            <li>
              To process call recordings and generate transcripts so you can
              review interactions with your customers
            </li>
            <li>
              To provide analytics and insights about your barbershop&apos;s call
              activity and booking performance
            </li>
            <li>
              To send transactional communications such as SMS booking
              confirmations to your customers
            </li>
            <li>
              To improve, personalize, and optimize our service and develop new
              features
            </li>
            <li>
              To detect, prevent, and address technical issues, fraud, or abuse
            </li>
            <li>To comply with legal obligations and enforce our terms</li>
          </ul>

          {/* 3. Third-Party Services */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            3. Third-Party Services
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            We rely on the following third-party service providers to deliver our
            platform. Each provider has its own privacy policy governing the data
            they process:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6 text-sm leading-relaxed text-warm-gray">
            <li>
              <strong className="text-cream/80">Clerk</strong> — Authentication
              and user management. Clerk processes your name, email address, and
              login credentials.
            </li>
            <li>
              <strong className="text-cream/80">Supabase</strong> — Database and
              backend infrastructure. Supabase stores account data, shop
              configurations, call logs, and booking records.
            </li>
            <li>
              <strong className="text-cream/80">Vapi</strong> — Voice AI
              platform. Vapi processes and records phone calls, generates
              transcripts, and powers our AI receptionist conversations.
            </li>
            <li>
              <strong className="text-cream/80">Square</strong> — Appointment
              scheduling and point-of-sale integration. Square receives booking
              data to create appointments on your business calendar.
            </li>
            <li>
              <strong className="text-cream/80">Twilio</strong> — SMS messaging.
              Twilio sends booking confirmation and reminder text messages to
              your customers.
            </li>
            <li>
              <strong className="text-cream/80">Vercel</strong> — Web hosting
              and deployment. Vercel hosts our application and may process
              standard web request data such as IP addresses.
            </li>
          </ul>
          <p className="mt-4 text-sm leading-relaxed text-warm-gray">
            We do not sell, rent, or trade your personal information to third
            parties for their marketing purposes.
          </p>

          {/* 4. Call Recording Disclosure */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            4. Call Recording Disclosure
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            Our AI receptionist service records phone calls made to your
            barbershop&apos;s BarberLine AI number. These recordings are
            essential for the service to function, as they enable transcript
            generation, quality assurance, and service improvement. Callers are
            informed at the beginning of each call that the conversation may be
            recorded. As a barbershop owner using our service, you are
            responsible for ensuring that call recording complies with all
            applicable federal and state laws in your jurisdiction.
          </p>

          {/* 5. Data Retention */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            5. Data Retention
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            We retain your account information for as long as your account is
            active or as needed to provide you with our services. Call recordings
            and transcripts are retained for up to 90 days, after which they are
            automatically deleted unless a longer retention period is required by
            law or requested by you. Booking data is retained for the duration of
            your subscription and for a reasonable period thereafter to support
            analytics and compliance. You may request deletion of your data at
            any time by contacting us.
          </p>

          {/* 6. Data Security */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            6. Data Security
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            We implement commercially reasonable technical and organizational
            security measures to protect your information against unauthorized
            access, alteration, disclosure, or destruction. These measures
            include encryption of data in transit and at rest, access controls,
            and regular security assessments. However, no method of transmission
            over the Internet or electronic storage is completely secure, and we
            cannot guarantee absolute security.
          </p>

          {/* 7. Your Rights */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            7. Your Rights
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            Depending on your jurisdiction, you may have certain rights regarding
            your personal information, including:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6 text-sm leading-relaxed text-warm-gray">
            <li>
              <strong className="text-cream/80">Access:</strong> You may request
              a copy of the personal information we hold about you.
            </li>
            <li>
              <strong className="text-cream/80">Correction:</strong> You may
              request that we correct inaccurate or incomplete personal
              information.
            </li>
            <li>
              <strong className="text-cream/80">Deletion:</strong> You may
              request that we delete your personal information, subject to
              certain legal exceptions.
            </li>
            <li>
              <strong className="text-cream/80">Portability:</strong> You may
              request a portable copy of your data in a commonly used format.
            </li>
            <li>
              <strong className="text-cream/80">Opt-Out:</strong> You may opt
              out of receiving promotional communications from us at any time.
            </li>
          </ul>
          <p className="mt-4 text-sm leading-relaxed text-warm-gray">
            To exercise any of these rights, please contact us at{" "}
            <a
              href="mailto:privacy@barberlineai.com"
              className="text-gold underline underline-offset-4 hover:text-gold-light"
            >
              privacy@barberlineai.com
            </a>
            . We will respond to your request within 30 days.
          </p>

          {/* 8. Children's Privacy */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            8. Children&apos;s Privacy
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            Our service is not directed to individuals under the age of 18. We
            do not knowingly collect personal information from children. If you
            believe we have inadvertently collected information from a child,
            please contact us immediately and we will take steps to delete such
            information.
          </p>

          {/* 9. Changes to This Policy */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            9. Changes to This Privacy Policy
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            We may update this Privacy Policy from time to time to reflect
            changes in our practices, technology, legal requirements, or other
            factors. When we make material changes, we will notify you by
            updating the &quot;Effective Date&quot; at the top of this page and,
            where appropriate, by sending you an email notification. We encourage
            you to review this Privacy Policy periodically.
          </p>

          {/* 10. Contact Us */}
          <h2 className="mt-12 mb-4 font-sans font-bold text-2xl text-cream">
            10. Contact Us
          </h2>
          <p className="text-sm leading-relaxed text-warm-gray">
            If you have any questions, concerns, or requests regarding this
            Privacy Policy or our data practices, please contact us at:
          </p>
          <div className="mt-4 border border-gold/10 bg-card p-6 text-sm leading-relaxed text-warm-gray">
            <p className="text-cream font-sans font-bold">BarberLine AI</p>
            <p className="mt-2">
              Email:{" "}
              <a
                href="mailto:privacy@barberlineai.com"
                className="text-gold underline underline-offset-4 hover:text-gold-light"
              >
                privacy@barberlineai.com
              </a>
            </p>
            <p className="mt-1">Location: Texas, United States</p>
          </div>
        </div>
      </div>
    </section>
  );
}
